platform:
  - x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'

environment:
  TEST_FILES: ExtraBuildTest,BuildTest,extraMetadataTest,filesTest,globTest,nsisUpdaterTest,oneClickInstallerTest,installerTest

install:
  - ps: Install-Product node 6 x64
  - node ./test/vendor/yarn.js --pure-lockfile

build: off

test_script:
  - node ./test/vendor/yarn.js test